### ISSUE TITLE
Is it possible to precisely mark a human with photoshop etc. for better results?

### ISSUE THREAD

**Issue by kucukti** [vt-vl-lab/3d-photo-inpainting#53]
https://www.dropbox.com/s/j7dtvxn5svwkuun/83295980_2548137572130531_1109801945073916914_n_zoom-in.mp4?dl=0

The hand is not marked correctly in this video. (it is like detached)
What I want to ask is that;  is it possible to make a precise marking with another tool like photoshop and then use the program with this marked jpg for a better result or is it a whole another story?

Sorry I'm just using the program for fun/hobby purposes, I may be asking a silly question.

**Comment by LemonATsu** [comment]
The artifact is most likely caused by the inaccurate depth estimation around the hand. One way to fix this (by hands) is to directly fiddle with the depth map. For example, you can manually photoshop (or use other tools) the estimated depth map so that you can have a crispy/correct depth estimates for humans/objects that are of your interests.
