### ISSUE TITLE
ERROR: Failed building wheel for cynetworkx

### ISSUE THREAD

**Issue by geopast** [vt-vl-lab/3d-photo-inpainting#98]
Following the install instructions exactly with the following:

Ubuntu 18.04.5
Anaconda 2020.7
Python 3.7.7

When running pip install -r requirements.txt, receive the error: ERROR: Failed building wheel for cynetworkx

Attempted to resolve with:

pip install Cython==3.0a5
pip install git+https://github.com/pattern-inc/cynetworkx.git
pip install -r requirements.txt

But error persists. Any suggestions on how to resolve?

**Comment by sjcobb** [comment]
Were there any other errors before that point? In my case, it was [issues with WSL](https://stackoverflow.com/questions/50729550/installing-g-on-windows-subsystem-for-linux) and I was also getting error: _unable to execute 'gcc': No such file or directory_.
 I found a similar issue and [followed the instructions here](https://github.com/watson-developer-cloud/python-sdk/issues/418#issuecomment-674038596) and ran 
```
sudo apt update
sudo apt install g++
pip install -r requirements.txt
```

**Comment by LemonATsu** [comment]
Close as the thread is no longer active.

**Comment by illtellyoulater** [comment]
I also have this problem, why has this thread been closed if a solution has not been found yet?

**Comment by L4nterns** [comment]
> I also have this problem, why has this thread been closed if a solution has not been found yet?

I have the same problem, did you solve it?

**Comment by illtellyoulater** [comment]
@beloved70020 I never found a solution... and probably I would have never found it along this route, because I just realized I inadvertently made changes to the .condarc file (which dictates which channel packages should be installed from) and because this altered file persisted multiple anaconda reinstalls it totally sent me off track...

So yeah, can't help you... all I can say, in case you are a new python user like me, is... next time you're lost don't forget to take a close look to that damn little file...

**Comment by duanjiding** [comment]
Building wheels for collected packages: cynetworkx
  Building wheel for cynetworkx (setup.py) ... \

**Comment by sumanttyagi** [comment]
@duanjiding any solution to this ?

**Comment by ipritom** [comment]
Solution suggested by @sjcobb  worked in WSL.
